- hosts: all
  roles:
    - name: Install Docker
      role: geerlingguy.docker
    - name: Install Docker package for Python
      role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: pip
            extra_args: "--upgrade"
          - name: docker
          - name: docker-compose
      become: true
    - name: app_purescript
      role: web_app
      vars: 
        web_app_base_path: "/opt/web_app"
        web_app_name: "app_purescript"
        web_app:
          registry: "dademd"
          image: "app_purescript"
          tag: "latest"
          port: 80
          external_port: 8003
          host: "0.0.0.0"
        web_app_full_wipe: false
    
  vars_files:
    - ../vault
    - ../vars.yml
  become_method: sudo
  become: true
