services:
  web:
    build:
      context: ./
    environment:
      - PORT=${DOCKER_PORT}
      - HOST=${HOST}
      - DATA_PATH=${DOCKER_DATA_PATH}
    ports:
      - ${HOST_PORT}:${DOCKER_PORT}
    volumes:
      - .:/app
      - ${LOCAL_DATA_PATH}:${DOCKER_DATA_PATH}
    # image: ${DOCKER_HUB_USERNAME}/app_python:latest
    image: app_python:latest

