[tool.poetry]
name = "app"
version = "0.1.0"
description = "app to show the current MSK time"
authors = ["Danila Danko <br4ch1st0chr0n3@gmail.com>"]

[tool.poetry.dependencies]
uvicorn = "^0.18.3"
fastapi = "^0.85.0"
python-dotenv = "^0.21.0"
python = "^3.10"

[tool.poetry.dev-dependencies]
pydantic = "^1.10.2"
Jinja2 = "^3.1.2"
mypy = "^0.971"
pylint = "^2.15.3"
uvicorn = "^0.18.3"
manage-fastapi = "^1.1.1"
black = "^22.8.0"
djlint = "^1.17.1"

[tool.poetry.scripts]
app = 'app.__init__:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
