web_app_base_path: "/opt/web_app"
web_app_name: "app_python"
web_app:
  registry: "dademd"
  image: "app_python"
  tag: "latest"
  port: 80
  external_port: 8002
  host: "0.0.0.0"
web_app_full_wipe: false