name: Cache each devshell

# Syntax
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#about-yaml-syntax-for-github-actions

description: cache flake inputs and shell

inputs:
  ROOT:
    description: a dir for which this action should be run
    required: true
  SHELLS:
    description: devShells names
    required: true
  CACHIX_AUTH_TOKEN:
    description: Cachix authorization token
    required: true

runs:
  using: composite
  steps:
    - uses: cachix/cachix-action@v10
      shell: bash
      with:
        name: ${{ env.cache }}
        authToken: "${{ inputs.CACHIX_AUTH_TOKEN }}"
    - name: Use cache
      shell: bash
      run: cachix use ${{ env.cache }}
    - name: Push inputs to cachix
      working-directory: ${{ inputs.ROOT }}
      shell: bash
      run: |
        nix flake archive --json \
          | jq -r '.path,(.inputs|to_entries[].value.path)' \
          | cachix push ${{ env.cache }}
    # - name: Push devshell to cachix
    #   working-directory: ${{ inputs.ROOT }}
    #   shell: bash
    #   run: |
    #     for devShell in ${{ inputs.SHELLS }} ;
    #     do
    #       nix develop .#$devShell --profile dev-profile
    #       cachix push ${{ inputs.CACHE }} dev-profile
    #     done
