kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.volumes.config.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
{{ .Files.Get "files/config.json" | indent 4}}