version: '3.9'
services:
  web:
    build: 
      context: ./
      args:
        - PORT=${DOCKER_PORT}
        - HOST=${HOST}
    ports:
      - ${HOST_PORT}:${DOCKER_PORT}
    volumes:
      - .:/app
