- changed_when: false
  check_mode: false
  command: '{{ docker_compose_path }} --version'
  failed_when: false
  name: Check current docker-compose version.
  register: docker_compose_vsn
- set_fact:
    docker_compose_current_version: '{{ docker_compose_vsn.stdout | regex_search(''(\d+(\.\d+)+)'') }}'
  when: docker_compose_vsn.stdout is defined
- file:
    path: '{{ docker_compose_path }}'
    state: absent
  name: Delete existing docker-compose version if it's different.
  when: |-
    >
                    docker_compose_current_version is defined
                    and (docker_compose_version | regex_replace('v', '')) not in docker_compose_current_version
- get_url:
    dest: '{{ docker_compose_path }}'
    mode: 755
    url: '{{ docker_compose_url }}'
  name: Install Docker Compose (if configured).
  when: |-
    >
                    (docker_compose_current_version is not defined)
                    or (docker_compose_current_version|length == 0)
                    or (docker_compose_current_version is version((docker_compose_version | regex_replace('v', '')), '<'))
