apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python-deployment
  labels:
    app: app-python
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
        - name: app-python
          image: deemp/app_python:latest
          ports:
            - containerPort: 8000
              protocol: TCP
              name: server-port
          envFrom:
            - configMapRef:
                name: app-python-config
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
