apiVersion: v1
kind: Service
metadata:
  name: app-python-service
  labels:
    app: app-python
spec:
  selector:
    app: app-python
  ports:
    - name: service-port
      protocol: TCP
      port: 8080
      targetPort: server-port
      nodePort: 30001
  type: NodePort