name: "Caching"

on:
  schedule:
    # https://crontab.guru/#30_5,17_*_*_*
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * *"
  pull_request:
  push:
  workflow_dispatch:

jobs:
  caching:
    name: Build on ${{ matrix.os }}
    env:
      # cache: br4ch1st0chr0n3
      # root: ./
      # app_purescript: app_purescript
      # app_python: app_python
      # root_devShells: "default codium"
      # app_purescript_devShells: "default dev"
      # app_python_devShells: "default dev"
      # each-devshell: ./.github/actions/each-devshell
      # DOCKER_HUB_USER: dademd
      IMAGE_TAG: v1
      # python: python
      # purescript: purescript
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://hydra.iohk.io https://haskell-language-server.cachix.org https://br4ch1st0chr0n3.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= haskell-language-server.cachix.org-1:juFfHrwkOxqIOZShtC4YC1uT1bBcq2RSvC7OMKx0Nz8= br4ch1st0chr0n3.cachix.org-1:o1FA93L5vL4LWi+jk2ECFk1L1rDlMoTH21R1FHtSKaU=
          install_url: https://releases.nixos.org/nix/nix-2.11.1/install
      - name: Log in to Docker Hub
        run: docker login -p ${{ secrets.DOCKER_HUB_PASSWORD }} -u ${{ secrets.DOCKER_HUB_USER }}
      - 
      - name: Log in to Cachix
        uses: cachix/cachix-action@v10
        with:
          name: ${{ secrets.CACHIX_CACHE }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Cache flakes  
        run: CACHIX_CACHE=${{ secrets.CACHIX_CACHE }} nix run
      # - name: Push ${{ env.app_python }} to Docker Hub
      #   uses: ./.github/actions/push-to-docker-hub
      #   with:
      #     PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      #     NAME: ${{ env.app_python }}
      #     TAG: ${{ github.sha }}
      #     SHELL: ${{ env.python }}
      
      # - name: Push ${{ env.app_purescript }} to Docker Hub
      #   uses: ./.github/actions/push-to-docker-hub
      #   with:
      #     PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      #     NAME: ${{ env.app_purescript }}
      #     TAG: ${{ github.sha }}
      #     SHELL: ${{ env.purescript }}

